### ISSUE TITLE
Response code=404

### ISSUE THREAD

**Issue by UltraHQ** [CyberTimon/stable-diffusion-discord-bot#5]
```
10/22/23 12:46:59: Started App
10/22/23 12:46:59: Connected to SD host on URL: http://127.0.0.1:7860
10/22/23 12:46:59: Did not receive correct response from SD host: http://127.0.0.1:7860
Response code=404
```

My SD is perfectly reachable over browser and this URL/Port.
Running on Windows 11, also disabled all SD Extensions, no difference.

API is enabled in SD Interface

**Comment by CyberTimon** [comment]
Hello!

I don't really know how to fix this issue - I can't reproduce it. Are you on the latest release of SD WebUi?

Kind regards,
Timon Käch

**Comment by UltraHQ** [comment]
> Hello!
> 
> I don't really know how to fix this issue - I can't reproduce it. Are you on the latest release of SD WebUi?
> 
> Kind regards,
> Timon Käch

Hi, yes. I'm on the latest SD from Automatic1111.

I also tried on my MacBook Pro running both, SD and the bot.
It has the same issue.

**Comment by CyberTimon** [comment]
I try to look into this more deep soon. I don't have A1111 on my machine right now. Thanks

**Comment by CyberTimon** [comment]
Were you able to fix this issue or is this still relevant?

**Comment by UltraHQ** [comment]
> Were you able to fix this issue or is this still relevant?

Hi, I was not able to fix it and have since given up. Not sure, if it's still relevant for others.

**Comment by CyberTimon** [comment]
Thanks for your answer. I moved on to different projects right now and haven't debugged this in depth. 
Will close this as stale, but if anyone else get's into this issue, feel free to comment on this / reopen another issue.
